services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: python server.py
    restart: unless-stopped

  collector:
    build: .
    env_file:
      - .env
    command: python collector.py
    restart: unless-stopped
    profiles:
      - collector
